### ISSUE TITLE
SKR version VCC not connected?

### ISSUE THREAD

**Issue by jeralm** [tehmaze/PowerBRRR#1]
As far as I can see, the SKR version has the VCC input pin disconnected from anything. Is that intentional? I can see that in the octopus version, VCC is connected to cap+ and the corner pin, so this seems to be an oversight

![image](https://user-images.githubusercontent.com/35611957/165682519-c70397ea-e517-4348-b032-6dbb51a85eb6.png)

**Comment by tehmaze** [comment]
Not sure why you are seeing this, because it is connected in my PCB editor:

<img width="313" alt="Screenshot 2022-04-28 at 10 19 47" src="https://user-images.githubusercontent.com/3327/165709627-b2a7f1d1-5325-448c-8d71-c1d1cef5b6a6.png">

**Comment by tehmaze** [comment]
Let me republish these GRBLs to make sure they are matching the latest version.
